package kotlinx.coroutines.internal

internal object ExceptionSuccessfullyProcessed : Exception
